[config]

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.config/quickshell/quickshell.json'

[templates.niri-colors]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/niri-colors.kdl'
